use_frameworks!

platform :ios, '10.0'

target 'UDPBroadcastListener_Example' do
  pod 'UDPBroadcastListener', :path => '../'

  target 'UDPBroadcastListener_Tests' do
    inherit! :search_paths

    
  end
end
