use_frameworks!

platform :ios, '10.0'

target 'UDPBroadcastListener_Example' do
  pod 'UDPBroadcastListener', :path => '../'
  pod 'TYHTestUtils',:git=>'https://github.com/pencilCool/TYHTestUtils.git'
  
  target 'UDPBroadcastListener_Tests' do
    inherit! :search_paths

    
  end
end
